apiVersion: v1
kind: ConfigMap
metadata:
  name: envvarsresourcesvc
data:
  DATASOURCE_CONNECTION_TIMEOUT: "30000"
  DATASOURCE_IDLE_TIMOUT: "600000"
  DATASOURCE_MAX_LIFETIME: "1800000"
  DATABASE_POOL_SIZE: "5"
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
  SPRING_DATASOURCE_URL: {{ .Values.env.SPRING_DATASOURCE_URL }}
  MULTI_TENANCY_TENANT_DATASOURCE_HOST: {{ .Values.env.MULTI_TENANCY_TENANT_DATASOURCE_HOST }}
  MULTI_TENANCY_TENANT_DATASOURCE_PORT: "27019"
  MONGO_DATASOURCE_USERNAME: {{ .Values.env.MONGO_DATASOURCE_USERNAME }}
  MONGO_DATASOURCE_PASSWORD: {{ .Values.env.MONGO_DATASOURCE_PASSWORD }}
  KC_ADMIN_USER: admin
  KC_ADMIN_PASSWORD: admin
  SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq-helm-chart:61616
  SPRING_ACTIVEMQ_USER: {{ .Values.env.SPRING_ACTIVEMQ_USER }}
  SPRING_ACTIVEMQ_PASSWORD: {{ .Values.env.SPRING_ACTIVEMQ_PASSWORD }}
  SPRING_ACTIVEMQ_TOPIC: PMO
  SPRING_ACTIVEMQ_QUEUE_EMAIL: emailQueue
  KEYCLOAK_REALM: pmo-admin-realm
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak-helm-chart:8080
  KEYCLOAK_RESOURCE: auth-service
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.env.KEYCLOAK_CREDENTIALS_SECRET }}
  AUTH_SERVICE_URL: http://authservice-helm-chart:8080/auth_service/api/users
  USER_SERVICE_URL: http://userservice-helm-chart:8080/user_service/api/users
  PROJECT_SERVICE_URL: http://projectservice-helm-chart:8080/project_service/api
  RESOURCE_UN_ASSIGN_SCHEDULE: '0 0 12 * * ?'
