apiVersion: v1
kind: ConfigMap
metadata:
  name: envvarsauthsvc
data:

  SPRING_DATASOURCE_URL: {{ .Values.env.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
  SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq-helm-chart:61616
  SPRING_ACTIVEMQ_USER: {{ .Values.env.SPRING_ACTIVEMQ_USER }}
  SPRING_ACTIVEMQ_PASSWORD: {{ .Values.env.SPRING_ACTIVEMQ_PASSWORD }}
  SPRING_ACTIVEMQ_TOPIC: PMO
  SPRING_ACTIVEMQ_QUEUE_EMAIL: emailQueue
  KC_ADMIN_USERNAME: admin
  KC_ADMIN_PASSWORD: admin
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak-helm-chart:8080
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.env.KEYCLOAK_CREDENTIALS_SECRET }}
  DATASOURCE_CONNECTION_TIMEOUT: "30000"
  DATASOURCE_IDLE_TIMOUT: "600000"
  DATASOURCE_MAX_LIFETIME: "1800000"
  DATABASE_POOL_SIZE: "5"
