apiVersion: v1
kind: ConfigMap
metadata:
  name: envvarsusersvc
data:
  MULTI_TENANCY_MASTER_DATASOURCE_URL: {{ .Values.env.MULTI_TENANCY_MASTER_DATASOURCE_URL }}
  MULTI_TENANCY_TENANT_DATASOURCE_URL_PREFIX: {{ .Values.env.MULTI_TENANCY_TENANT_DATASOURCE_URL_PREFIX }}
  DATASOURCE_USERNAME: {{ .Values.env.DATASOURCE_USERNAME }}
  DATASOURCE_PASSWORD: {{ .Values.env.DATASOURCE_PASSWORD }}
  KC_ADMIN_USER: pmo-admin
  KC_ADMIN_PASSWORD: admin
  SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq-helm-chart:61616
  SPRING_ACTIVEMQ_USER: {{ .Values.env.SPRING_ACTIVEMQ_USER }}
  SPRING_ACTIVEMQ_PASSWORD: {{ .Values.env.SPRING_ACTIVEMQ_PASSWORD }}
  SPRING_ACTIVEMQ_TOPIC: PMO
  SPRING_ACTIVEMQ_QUEUE_EMAIL: emailQueue
  FRONT_END_BASE_URL: {{ .Values.env.FRONT_END_BASE_URL }}
  FRONT_END_BASE_PROTOCOL: {{ .Values.env.FRONT_END_BASE_PROTOCOL }}
  AUTH_SERVICE_URL: http://authservice-helm-chart:8080/auth_service/api/users
  SUBSCRIPTION_SERVICE_URL: http://subscriptionservice-helm-chart:8080/subscription_service/api/subscriptions
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak-helm-chart:8080
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.env.KEYCLOAK_CREDENTIALS_SECRET }}
  CLOUDFLARE_SERVICE_BASE_URL: "https://api.cloudflare.com/client/v4/zones/"
  CLOUDFLARE_SERVICE_READTIMEOUT: "30000"
  CLOUDFLARE_SERVICE_CONNECTIONTIIMEOUT: "30000"
  CLOUDFLARE_SERVICE_FOLLOWREDIRECTS: "false"
  CLOUDFLARE_SERVICE_TTL: "3600"
  CLOUDFLARE_ZONE-ID: "db668ccfe84ba997bc18b2f715c949ca/"
  CLOUDFLARE_ACCESS-TOKEN: "Bearer y80Y-DU-7_AwUElTXXVAksFuXYi7xlvW1zFtBzf-"
  CLOUDFLARE_DOMAIN: {{ .Values.env.CLOUDFLARE_DOMAIN }}
  SERVER_ENVIRONMENT: {{ .Values.env.SERVER_ENVIRONMENT }}
 

