apiVersion: v1
data:
  .dockerconfigjson: {{ "{\"auths\": {\"nexus.mynisum.com:2376\": {\"username\": \"pmotracker@nisum.com\", \"password\": \"Nisum@12345\"}}}" | b64enc }}
kind: Secret
metadata:
  name: dockercredpaymentgatewaysvc
type: kubernetes.io/dockerconfigjson
