apiVersion: v1
kind: ConfigMap
metadata:
  name: envvarssubscriptionsvc
data:
  MULTI_TENANCY_MASTER_DATASOURCE_URL: {{ .Values.env.MULTI_TENANCY_MASTER_DATASOURCE_URL }}
  MULTI_TENANCY_TENANT_DATASOURCE_URL_PREFIX: {{ .Values.env.MULTI_TENANCY_TENANT_DATASOURCE_URL_PREFIX }}
  DATASOURCE_USERNAME: {{ .Values.env.DATASOURCE_USERNAME }}
  DATASOURCE_PASSWORD: {{ .Values.env.DATASOURCE_PASSWORD }}
  KC_ADMIN_USER: pmo-admin
  KC_ADMIN_PASSWORD: admin
  SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq-helm-chart:61616
  SPRING_ACTIVEMQ_USER: {{ .Values.env.SPRING_ACTIVEMQ_USER }}
  SPRING_ACTIVEMQ_PASSWORD: {{ .Values.env.SPRING_ACTIVEMQ_PASSWORD }}
  SPRING_ACTIVEMQ_TOPIC: PMO
  SPRING_ACTIVEMQ_QUEUE_EMAIL: emailQueue
  AUTH_SERVICE_URL: http://authservice-helm-chart:8080/auth_service/api/users
  USER_SERVICE_URL: http://userservice-helm-chart:8080/user_service/api/users
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak-helm-chart:8080
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.env.KEYCLOAK_CREDENTIALS_SECRET }}
  INVOICE_NOTIFICATION_SCHEDULE: '0 0 13 * * ?'
  INVOICE_PAYMENT_GATEWAY_QUEUE_SCHEDULE: '0 45 18 * * ?'
  SUBBSCRIPTION_NOTIFICATION_SCHEDULE: '0 0 19 * * ?'
  INVOICE_NOTIFICATION_DAYSBEFOREONOTIFYCUSTOMER: '3'
  BIGECIMAL_PRRECISION: '65'
  BIGDECIMAL_ROUND_OFF_PLACES: '2'
  KEYCLOAK_PMO_OFFICE_CLIENT_SECRET: {{ .Values.env.KEYCLOAK_PMO_OFFICE_CLIENT_SECRET }}
  KEYCLOAK_PMO_OFFICE_PUBLIC_KEY: {{ .Values.env.KEYCLOAK_PMO_OFFICE_PUBLIC_KEY }}
