apiVersion: v1
data:
#  .dockerconfigjson: {{ "{\"auths\": {\"nexus.mynisum.com:2376\": {\"username\": \"pmotracker@nisum.com\", \"password\": \"Nisum@12345\"}}}" | b64enc }}
  .dockerconfigjson: {{ "{\"auths\": {\"nexus.mynisum.com:2376\": {\"username\": \"pmotracker@nisum.com\", \"password\": \"Nisum@12345\"}}}"  | b64enc }}
kind: Secret
metadata:
  name: dockercredsubscriptionsvc
type: kubernetes.io/dockerconfigjson
