# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/pmogcp/cloudpmoimgregistry/userservice
  tag: 5936ff
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP # NodePort
    #exposePort: 30409
  targetPort: 8085
  internalPort: 8080

env:
  MULTI_TENANCY_MASTER_DATASOURCE_URL: jdbc:mysql://34.148.125.185:3309/master
  MULTI_TENANCY_TENANT_DATASOURCE_URL_PREFIX: jdbc:mysql://34.148.125.185:3309/userservice_
  DATASOURCE_USERNAME: dummy
  DATASOURCE_PASSWORD: dummy
  SPRING_ACTIVEMQ_USER: dummy
  SPRING_ACTIVEMQ_PASSWORD: dummy
  KEYCLOAK_CREDENTIALS_SECRET: dummy
  FRONT_END_BASE_URL: ".uat.pmotracker.com"
  FRONT_END_BASE_PROTOCOL: "https://"
  CLOUDFLARE_DOMAIN: "34.73.117.35"
  SERVER_ENVIRONMENT: "uat"

#  SPRING_DATASOURCE_USERNAME: dummy
#  SPRING_DATASOURCE_PASSWORD: dummy
#  SPRING_ACTIVEMQ_USER: dummy
#  SPRING_ACTIVEMQ_PASSWORD: dummy
#  KEYCLOAK_CREDENTIALS_SECRET: dummy
#  SPRING_DATASOURCE_URL: "jdbc:mysql://34.148.125.185:3306/userservice?createDatabaseIfNotExist=true"
#  FRONT_END_BASE_URL: "https://uat.pmotracker.com"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
